"""add order shipping snapshot columns

Revision ID: d1387b3de3e6
Revises: 0bf76e3d4ccc
Create Date: 2026-09-21 23:47:28.217581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1387b3de3e6'
down_revision: Union[str, None] = '0bf76e3d4ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_full_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_line1', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_line2', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_state', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_pincode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_pincode')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_line2')
    op.drop_column('orders', 'shipping_line1')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_full_name')
    # ### end Alembic commands ###
